import 'package:foottalents/Models/players.dart';

import 'Models/team.dart';
import 'models/team_stats.dart';

List<Player> players = [
  Player(
    id: "1",
    firstName: "Obay7lo",
    lastName: "Hafez",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "obay@gmail.com",
    nationality: "Syrian",
    city: "Damascus",
    birthDate: "1990-01-01",
    height: "177",
    weight: "63",
    position: "Forward",
    secondaryPosition: "Midfielder",
    foot: "Right",
  ),
  Player(
    id: "2",
    firstName: "John",
    lastName: "Doe",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "johndoe@gmail.com",
    nationality: "American",
    city: "New York",
    birthDate: "1992-05-12",
    height: "185",
    weight: "78",
    position: "Defender",
    secondaryPosition: "Midfielder",
    foot: "Right",
  ),
  Player(
    id: "3",
    firstName: "Emma",
    lastName: "Smith",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "emmasmith@gmail.com",
    nationality: "British",
    city: "London",
    birthDate: "1995-09-20",
    height: "170",
    weight: "60",
    position: "Midfielder",
    secondaryPosition: "Forward",
    foot: "Left",
  ),
  Player(
    id: "4",
    firstName: "Max",
    lastName: "Müller",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "maxmuller@gmail.com",
    nationality: "German",
    city: "Berlin",
    birthDate: "1993-07-08",
    height: "182",
    weight: "75",
    position: "Forward",
    secondaryPosition: "Midfielder",
    foot: "Right",
  ),
  Player(
    id: "5",
    firstName: "Sophia",
    lastName: "Garcia",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "sophiagarcia@gmail.com",
    nationality: "Spanish",
    city: "Madrid",
    birthDate: "1994-04-15",
    height: "168",
    weight: "58",
    position: "Defender",
    secondaryPosition: "Midfielder",
    foot: "Right",
  ),
  Player(
    id: "6",
    firstName: "Yuki",
    lastName: "Tanaka",
    imageUrl:
        "https://i.ibb.co/Ry3DMYR/Whats-App-Image-2023-06-05-at-16-17-08.jpg",
    email: "yukitanaka@gmail.com",
    nationality: "Japanese",
    city: "Tokyo",
    birthDate: "1991-12-03",
    height: "175",
    weight: "65",
    position: "Midfielder",
    secondaryPosition: "Forward",
    foot: "Right",
  ),
];

List<Team> top5teams = [];
List<Team> teams = [
  Team(
    id: "1",
    name: "Cobra",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "Syria",
    city: "Damascus",
    createDate: "2020-05-05",
    beforePointScore: "455",
    currentPointScore: "750",
    status: "2022-05-05",
  ),
  Team(
    id: "2",
    name: "Tigers",
    imageUrl: "https://askastrology.com/wp-content/uploads/2018/10/HOR_108_Tiger.jpg",
    country: "USA",
    city: "New York",
    createDate: "2019-10-10",
    beforePointScore: "320",
    currentPointScore: "550",
    status: "2022-09-30",
  ),
  Team(
    id: "3",
    name: "Dragons",
    imageUrl: "https://c8.alamy.com/comp/J3PA47/chinese-dragon-tattoo-design-J3PA47.jpg",
    country: "China",
    city: "Beijing",
    createDate: "2018-07-15",
    beforePointScore: "580",
    currentPointScore: "900",
    status: "2022-12-31",
  ),
  Team(
    id: "4",
    name: "Panthers",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "Brazil",
    city: "Rio de Janeiro",
    createDate: "2017-03-20",
    beforePointScore: "400",
    currentPointScore: "680",
    status: "2022-11-15",
  ),
  Team(
    id: "5",
    name: "Lions",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "South Africa",
    city: "Johannesburg",
    createDate: "2016-09-05",
    beforePointScore: "520",
    currentPointScore: "820",
    status: "2022-08-20",
  ),
  Team(
    id: "6",
    name: "Eagles",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "Canada",
    city: "Toronto",
    createDate: "2015-05-25",
    beforePointScore: "610",
    currentPointScore: "950",
    status: "2022-07-10",
  ),
  Team(
    id: "7",
    name: "Sharks",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "Australia",
    city: "Sydney",
    createDate: "2014-01-12",
    beforePointScore: "480",
    currentPointScore: "760",
    status: "2022-06-05",
  ),
  Team(
    id: "8",
    name: "Bears",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "Russia",
    city: "Moscow",
    createDate: "2013-08-18",
    beforePointScore: "540",
    currentPointScore: "880",
    status: "2022-05-01",
  ),
  Team(
    id: "9",
    name: "Wolves",
    imageUrl: "https://i.ibb.co/qp4GqHF/HD-wallpaper-cobra-kai-logo.jpg",
    country: "France",
    city: "Paris",
    createDate: "2012-04-07",
    beforePointScore: "390",
    currentPointScore: "650",
    status: "2022-04-10",
  ),
];


List<TeamStats> top5Teams = [
  TeamStats(
    team: teams[0],
    playedMatches: 20,
    won: 15,
    loss: 5,
    GF: 40,
    GA: 20,
  ),
  TeamStats(
    team: teams[1],
    playedMatches: 18,
    won: 12,
    loss: 6,
    GF: 35,
    GA: 18,
  ),
  TeamStats(
    team: teams[2],
    playedMatches: 22,
    won: 17,
    loss: 5,
    GF: 50,
    GA: 15,
  ),
  TeamStats(
    team: teams[3],
    playedMatches: 21,
    won: 13,
    loss: 8,
    GF: 45,
    GA: 25,
  ),
  TeamStats(
    team: teams[4],
    playedMatches: 19,
    won: 16,
    loss: 3,
    GF: 55,
    GA: 10,
  ),
];
